logging:
  level: DEBUG

monitoring:
  check_every_secs: 60

database:
  uri: sqlite+aiosqlite:///./db.sqlite

telegram:
  bot_token: "[ADD YOUR OWN TOKEN]"
  channel_ids:
    - [ADD YOUR OWN CHANNEL ID]