---
logging:
  level: DEBUG

networking:
  service_name: sys-subsystem-net-devices-wlan0.device

filesystem:
  user: roman
  group: roman

monitoring:
  check_every_secs: 60

telegram:
  bot_token: REPLACEME
  channel_ids: [1000]