deploy: ## Deploy Hirsh to RaspberryPI
	@echo "🚚 Deploying to RPI.."
	@ansible-playbook -i hosts deploy.yaml

uninstall: ## Deploy Hirsh to RaspberryPI
	@echo "🧹 Uninstalling Hirsh.."
	@ansible-playbook -i hosts uninstall.yaml
