---
- name: install apt dependencies
  apt: pkg={{ item }} update_cache=yes
  with_items:
    - git
    - python3-dev
    - python3-venv
#- name: install poetry
#  shell: curl -sSL https://install.python-poetry.org | python3 -